language: python
python:
  - 3.8
script:
  - pytest
before_install:
  - "echo before install"
  - "sudo apt-get install gcc gfortran"
  - "pip install -U pip"
install:
  - "pip install .[extra,test]"
