[build-system]
    build-backend = 'mesonpy'
    requires = [
        "wheel",
        "meson-python>=0.8.0",
        "setuptools<60.0",  # Do not increase, 60.0 enables vendored distutils
        # "oldest-supported-numpy; python_version>'3.9'",
        # "numpy; python_version<='3.9'"
        "numpy",
    ]

[project]
name = "wavespectra"
version = "3.8.2"
authors = [
  { name = "MetOcean Solutions", email = "support@metocean.co.nz" },
]
description = "Ocean wave spectra tools for Python"
readme = "README.rst"
license = { file = "LICENSE.txt" }
requires-python = ">=3.8,<3.13"
dependencies = [
  "numpy",
  "pandas",
  "xarray>=0.16.1,<=2023.01.0",
  "python-dateutil",
  "dask>=0.17.1",
  "toolz",
  "sortedcontainers",
  "scipy",
  "pyaml"
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Visualization",
]

